###
GET http://localhost:5072/api/Projects
Accept: application/json    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOTE3ODNhYy1hZDkwLTQxYzMtYjM2YS1lMjc0ZTMzNjRjNjEiLCJlbWFpbCI6ImFkbWluQHNraWxsc25hcC5pbyIsImp0aSI6ImZhMTE4NDZmLTZmYjAtNGQ1NC1hMDBiLTdiOGIzM2MxNGZlNiIsImlzcyI6IlNraWxsU25hcC5BcGkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc1MTA3NzY1NSwiYXVkIjoiU2tpbGxTbmFwLkNsaWVudCJ9.8NeL9dQ9PjeZUBT13J6aFp2cFFA9SDMhz3rKD03iDDg

###
GET http://localhost:5072/api/test
Accept: application/json    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOTE3ODNhYy1hZDkwLTQxYzMtYjM2YS1lMjc0ZTMzNjRjNjEiLCJlbWFpbCI6ImFkbWluQHNraWxsc25hcC5pbyIsImp0aSI6IjFkYWJkNmIzLTY2YjAtNDQ0Zi1hODg3LWVmMjM3NzVkZWY3NyIsImlzcyI6IlNraWxsU25hcC5BcGkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc1MTA3ODAwNiwiYXVkIjoiU2tpbGxTbmFwLkNsaWVudCJ9.mDjlem1TBQcHi2yTgpF8MFNHhIwqHpASZwqa68pmZaQ